modLoader = "lowcodefml"
loaderVersion = "*"
issueTrackerURL = "${issuesUrl}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "${logo}"
logoBlur = false
displayURL="${homeUrl}"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
