package io.github.leawind.systemstoragelib.v1.api;

import io.github.leawind.systemstoragelib.v1.api.managers.CredentialStore;
import io.github.leawind.systemstoragelib.v1.api.managers.StorageManager;
import org.slf4j.Logger;

/// Defines storage locations for different types of data within a specific scope.
/// Each scope provides access to storage managers tailored for different data categories.
///
/// | Method | Condition |
/// | - | - |
/// | {@link #credentials} | Sensitive credentials |
/// | {@link #config} | Configuration files |
/// | {@link #data} | Persistent + shareable across machines |
/// | {@link #dataLocal} | Persistent + machine-local (or renewable but costly to regenerate) |
/// | {@link #cache} | Renewable + cheap to regenerate |
///
/// @apiNote Each category must have different directory.
public interface ScopeStorage {
  String scope();

  Logger logger();

  CredentialStore credentials();

  /// Configuration storage
  ///
  /// For user-specific configuration files.
  StorageManager config();

  /// Persistent data storage
  ///
  /// For user-specific data files that may be shared across machines
  StorageManager data();

  /// Local data storage
  ///
  /// Unlike {@link #data()}, the contents of this directory are specific to the local machine and
  /// should NOT be shared across machines (e.g., via sync or roaming profiles).
  /// Use this for data that is tied to the local environment, such as machine-specific state or
  /// derived data.
  StorageManager dataLocal();

  /// Non-essential cache storage
  ///
  /// for non-essential data files that can be regenerated by the application.
  /// Applications should be able to recover if files in this directory are deleted.
  StorageManager cache();
}
