name: Publish to Modrinth

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish to Modrinth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Permission to Execute Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          loaders: |
            fabric
            neoforge
            forge
            quilt

          modrinth-id: t07y8PBv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
