name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Permission to Execute Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          loaders: |
            fabric
            forge
            quilt

          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: t07y8PBv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1556147
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
